### ISSUE TITLE
Error when Generate Atom for Facebook Pages as Facebook Business User

### ISSUE THREAD

**Issue by edwardchanjw** [snarfed/facebook-atom#1]
As titles, it show 

```
500 Internal Server Error
The server has either erred or is incapable of performing the requested operation.
```

Btw i come across for open standards for federation social network and your work are great for the purpose.

**Comment by snarfed** [comment]
thanks for the kind words! i've never used facebook as a business user, so i might need some help. could you give me some more information on how specifically to reproduce this?

**Comment by snarfed** [comment]
closing as obsolete now that we scrape instead of using the API.
