### ISSUE TITLE
readers show duplicate post (with same id) when content changes

### ISSUE THREAD

**Issue by snarfed** [snarfed/facebook-atom#11]
thanks to @kevinmarks for nudging me about this. evidently some readers show a story multiple times, even when its id is the same. i've seen this in my feed reader, newsblur, for e.g. https://m.facebook.com/photo.php?fbid=10104632133214713&id=1227885&set=a.10100480874834783.2882922.1227885 .

my best guess is that the content is changing, e.g. the number of comments and likes, so readers show the story again even though the id is the same. newsblur actually shows it as a new story, ie it shows both the old version and the new version in the stream.

¯\_(ツ)_/¯

**Comment by bear** [comment]
i've seen this when a URL is used for an ID and has items in the path, heck even in the domain name, that cause it to be a different IRI but resolves to the same article or item

**Comment by snarfed** [comment]
huh. thanks for looking @bear! i believe the ids in this case are char for char identical, both are the URL in the description. i'll double check though!

**Comment by bear** [comment]
if you want to send me two examples of the <item> that are dupes I can look at it

**Comment by snarfed** [comment]
one quirk is that the `&`s have to be entity encoded, so the exact id is actually `https://m.facebook.com/photo.php?fbid=10104632133214713&amp;id=1227885&amp;set=a.10100480874834783.2882922.1227885`. not sure if that's the kind of thing you're thinking of. if so, disappointing. :disappointed:

**Comment by bear** [comment]
well, it depends on how it is in the xml file specifically _and_ how the feed reader decides to compare, some go against the spec and try to disambiguate the url while the spec calls for a straight up string compare

**Comment by snarfed** [comment]
got it. yay complexity!

here's a snippet of the feed with hopefully everything that matters:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<feed xml:lang="en-US" xmlns="http://www.w3.org/2005/Atom">
<id>https://facebook-atom.appspot.com/</id>
<title>facebook-atom feed</title>
<logo>https://static.xx.fbcdn.net/rsrc.php/v2/yp/r/eZuLK-TGwK1.png</logo>
<updated>2015-09-21T21:09:11.664910Z</updated>

<link href="https://m.facebook.com/" rel="alternate" type="text/html" />
<link href="https://facebook-atom.appspot.com/"
      rel="self" type="application/atom+xml" />

<entry>
  <id>https://m.facebook.com/photo.php?fbid=10104632133214713&amp;id=1227885&amp;set=a.10100480874834783.2882922.1227885</id>
  <link rel="alternate" type="text/html" href="https://m.facebook.com/photo.php?fbid=10104632133214713&amp;id=1227885&amp;set=a.10100480874834783.2882922.1227885" />
  <title>...</title>
  <content type="xhtml">
  <div xmlns="http://www.w3.org/1999/xhtml">
    <div class="cv cx dy" id="u_0_8">
    ...
    </div>
  </content>
</entry>
...
</feed>
```

**Comment by bear** [comment]
The atom:id allows for % encoding but how that is handled can cause issues as %7E and %7e would cause the id to be treated as different as could `'&amp;'` vs `'&'` 

I would need to see both entries to know for sure

**Comment by snarfed** [comment]
ok this is annoying me now, i may tackle it soon.

@kevinmarks suggested using the `If-Last-Modified` header (and friends). interesting idea! not entirely sure it would work though, since old stories could still dupe themselves whenever there's a new story.

current thought: strip the comment/like/reshare counts (or entire sections) along with any other parts that can change.

**Comment by bear** [comment]
hmm, are the including an <updated/> value for the <entry/> items that change? if not you can use that.

otherwise yea, doing a HEAD request with an if-last-modified value set to the feed's <update/> value might work.

**Comment by kevinmarks** [comment]
I'm not sure that Facebook-atom is caching between fetches; it could construct it's own etag and Last-Modified headers (i.e. ignoring non-content updates for both) and then check the returned ones in the GET to decide whether the rare new things to send. How it works for a client is documented well here: http://pythonhosted.org/feedparser/http-etag.html

**Comment by snarfed** [comment]
sorry, yeah, i tried to address this before, but i was probably unclear:

> not entirely sure it would work though, since old stories could still dupe themselves whenever there's a new story.

to elaborate, if i use the etags headers, when FB _does_ have new stories, i expect it will still return me a full page's worth of stories, including ones i've seen before. (this is worth testing, since it's an assumption, but i'm pretty confident.) when that happens, i'd still serve all of the stories in that full page, both new and old, so the old ones will still have the chance to dupe themselves if they've gotten more likes or comments since i last served them.

@kevinmarks it sounds like you were also implying i should store each user's seen ids and only serve an story with a given id once. that'd take a bit of work - which is fine - but it also assumes users only use a single reader each, and that reader perfectly captures all stories on each fetch...which may often be true, but it's a little scary.

given that, stripping the likes and comments still seems a bit safer...

**Comment by snarfed** [comment]
looks like stripping likes and comments may have worked. my own FB feed has been dupe-free since that change, and @kevinmarks says his looks better too. tentatively closing!

**Comment by snarfed** [comment]
lots of dupes recently. :( reopening.
