### ISSUE TITLE
Seems to have different stories at top every time I refresh

### ISSUE THREAD

**Issue by singpolyma** [snarfed/facebook-atom#15]
Is it using the "most recent" feed or the sorted by magic content?  Is the former even possible?

**Comment by singpolyma** [comment]
I visited http://m.facebook.com/?sk=h_chr and now it seems to be in most recent order in the feed... I guess because the cookie got changed maybe?

**Comment by snarfed** [comment]
heh, yeah, the feed itself will be pretty underwhelming if you look at its literal contents across requests. it scrapes m.facebook.com, which returns ten items per fetch using the standard news feed algorithm (afaik), so it will change from one fetch to another based on lots of factors.

given that, it definitely can't claim to be comprehensive or deterministic. in practice though, if you read it in a feed reader that merges and sorts by time and dedupes by id, it usually works pretty well.

**Comment by snarfed** [comment]
oh, and i don't _think_ a cookie change should have affected it, but the visit itself probably did, since fb remembers what you've "seen". i can't say for sure, of course.

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!

**Comment by singpolyma** [comment]
Went back today, seemed to be in random order again.  visiting the mobile site did not change this.  Went to facebook desktop on the same browser that I got the cookie from and selected "most recent" -- now the feed seems to have a stable order for awhile.  So there is something in the selection that triggers this maybe?  Stored on their server but associated with the cookie values
