### ISSUE TITLE
switch from mobile version

### ISSUE THREAD

**Issue by mblaney** [snarfed/facebook-atom#16]
hey @snarfed thanks for making this it's great! :-)

How would you feel about switching from m.facebook.com to facebook.com? Clicking through from my reader on a desktop doesn't redirect, but I'm guessing the opposite will work, clicking a facebook.com link (without the m. subdomain) will probably do "the right thing" on a mobile. thoughts?

**Comment by snarfed** [comment]
yes! the m.facebook.com links have annoyed me forever too. rewriting them is nontrivial, though. many of them don't work if you just drop the m. still, I'll see what i can do.

**Comment by mblaney** [comment]
cool, I'm happy to help, just wanted to make sure it would get merged :-)

I haven't looked at this project before, so not quite sure how it interacts with granary. Are all the facebook links found in this repo? From my own experience removing the 'm.' in a link only works for photo posts.

**Comment by snarfed** [comment]
thanks for offering to help! this project used to use granary, but then facebook turned off the ability to read your news feed in the API, so now it scrapes and converts internally. everything's in [`cookie.py`](https://github.com/snarfed/facebook-atom/blob/master/cookie.py); it fetches https://m.facebook.com/, parses it with BeautifulSoup, extracts out and transforms the stories, and renders Atom.

setup instructions are at https://github.com/snarfed/facebook-atom#development . feel free to ping me with q's!

**Comment by mblaney** [comment]
setup went pretty smoothly, though the command: pip install -r requirements.txt ended with:
`ImportError: No module named six.moves`

Not sure if that's related to what happened next, which was the web app launched ok but entering my details and trying to load the feed ended with:
`Traceback (most recent call last):`
`  File "/home/mal/work/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())`
`  File "/home/mal/work/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)`
`  File "/home/mal/work/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])`
`  File "/home/mal/work/facebook-atom/cookie.py", line 89, in <module>
    class CookieHandler(handlers.ModernHandler):`
`  File "/home/mal/work/facebook-atom/cookie.py", line 92, in CookieHandler
    @handlers.memcache_response(CACHE_EXPIRATION)`
`AttributeError: 'module' object has no attribute 'memcache_response'`
`INFO     2017-01-27 01:28:28,177 module.py:787] default: "GET /cookie?c_user=####&xs=#### HTTP/1.1" 500 -`

Hopefully that means something to you?

**Comment by snarfed** [comment]
hey, great! and oops, sorry, that's my fault. fixed now, just `git pull` and then run `pip install ...` again.

**Comment by mblaney** [comment]
Hi @snarfed, I'm thinking of closing this issue because desktop facebook is js;dr :-(

My initial thought was stick to the mobile version but find a way to convert links, but no success there. The only other way I see is a headless browser such as phantomjs or spynner but that seems like too much work to solve this particular problem. If you have any other thoughts let me know, or if you're interested in looking into it I can at least provide the changes required to detect that I'm logged in.

**Comment by snarfed** [comment]
thanks for the update! and wow, you don't think there's any way to convert m.facebook.com links to facebook.com programmatically, without fetching and scraping more html? that's surprising and disappointing if so.

(also i think cookie.py:113-121 already detects whether we successfully logged in, right? or do your changes do something else?)

**Comment by mblaney** [comment]
ok maybe I spoke too soon.... I just tried something that should've been obvious, which is find a permalink on both versions and compare them. It looks like a can swap `m.facebook.com/story.php` to `www.facebook.com/permalink.php` and the query string will work. I think I'll keep trying that for a bit and see what other links can be modified.

Your login check is mobile specific. The logout link in desktop mode is generated by javascript so the closest thing I could find was a div with id = logoutMenu.

**Comment by snarfed** [comment]
ahh i see, you tried scraping `facebook.com`. yeah, converting links is definitely the way to go. glad it's working so far!

**Comment by mblaney** [comment]
sorry I sort of dropped the ball on this one... now that I know only the mobile version is scrapable, I'm not sure it's worth messing with the output? If you think it would be useful, I'm still happy to make the change, but I'm now thinking that my reader could just rewrite the links? It knows if it's in desktop or mobile mode, so it could just rewrite links in desktop mode. (I know this doesn't help other readers, but they could make the same change if they wanted to.)

**Comment by snarfed** [comment]
hey, no worries! totally up to you. if you've figured out the mapping for different types of links, i think that's actually the hard part. feel free to post that here, and I'll happily implement it!

**Comment by mblaney** [comment]
All good, but we can't both make the change... if we change it here then there won't be any more mobile links for me to replace in my reader! :-) So I'm pretty sure #17 is all that's required. I've been clicking through from my reader for a few weeks now, and only the /story.php links cause a problem when switching `m` to `www`.

**Comment by snarfed** [comment]
awesome, thank you! merged and deployed!

spot checking a few links in my feed, the only unhappy one i found is: https://m.facebook.com/story.php?story_fbid=10102905392237463&id=203128

from: https://m.facebook.com/story.php?story_fbid=10102905392237463&id=203128

...but it's unhappy as both m.facebook.com and www.facebook.com, so ¯\\\_(ツ)\_/¯

**Comment by mblaney** [comment]
no worries, thanks for merging. I tried the link you had trouble with but worked fine for me?

I also wanted to switch photos for higher resolution ones, but haven't found a way to do that yet.
