### ISSUE TITLE
unescaped ampersands in titles

### ISSUE THREAD

**Issue by mblaney** [snarfed/facebook-atom#19]
hi @snarfed I'm seeing unescaped ampersands in titles, which my parser is bailing on.

What do you think of the idea of using the same technique as content, and putting type="xhtml" on title too?

**Comment by snarfed** [comment]
hey, thanks for filing, and sorry for the trouble! hmm, i could do the full fledged embedded xhtml thing like content, but title is just a string with no markup, so I'm inclined to do `xml.sax.saxutils.escape` instead, like i currently do with `url`. what do you think?

**Comment by mblaney** [comment]
ah yeah that makes more sense. want a pull request or are you happy to do that?

**Comment by snarfed** [comment]
sure, go for it! i won't be at a computer for a bit, so feel free to send a PR if you want, otherwise I'll get to it soon.

**Comment by snarfed** [comment]
fixed by #20.
