### ISSUE TITLE
opt out of blacklisting

### ISSUE THREAD

**Issue by Sup4m0nkey** [snarfed/facebook-atom#21]
"Most stories that aren't actual posts from your friends - X commented on this, Y liked this, A and B are friends, etc. - are hidden. Let us know if you want to see any of them, and we'll consider it!"
Well, I may be the only one interested, but I'd want to see those things in my feed.
Thank's for considering the idea ! =P

**Comment by Sup4m0nkey** [comment]
Actually, I'd like to see anything from my friends.
I'll explain my problem :
I think I did everything as it should be done :
https://facebook-atom.appspot.com/
I'm using Opera, so : preferences, searching cookies, found c_user, that says "name = c_user", "content = [a-bunch-of-numbers]", "domain = .facebook.com" etc.
Copied the [bunch of numbers] and pasted it in the right box.
Did the same for the xs cookie, it's a bunch of letters and numbers this time, copy-pasted it in the other box.
It gives me a link, that I used with QuiteRSS. It only shows me hte feeds from pages I like, but not from my friends.
Tried with rssguard and tried clickin the link to open it in opera, same problem.
Am I doing something wrong ? Is this a bug ?
Thanks in advance.

**Comment by snarfed** [comment]
thanks for the nudge! it's easy to add an option to show you everything, including "commented on," "likes this," etc. i'll do that.

if you're seeing items in your feed, it's working. it only shows the most recent 5-10, so it might be that all of those for you are from pages, not friends, or maybe you've unfollowed many of your friends. give it time. 😁 it's the same items as in https://m.facebook.com/ , so you can always compare there.

**Comment by Sup4m0nkey** [comment]
So, two things :
1) When I check on m.facebook.com and compare, both don't show the same thing. How can I troubleshoot this ? I've tried from QuiteRSS and in Opera, and they show the same thing.
2) I'd like the feed to show me the same as my "most recent" newsfeed in facebook. Is this possible ?
Thanks for your quick answer, I didn't expect it so soon =)

**Comment by snarfed** [comment]
i've added a way to skip the per post blacklisting. add `&all=true` to the end of your feed URL, and it will include all posts from https://m.facebook.com/ that it can. try that and compare?

as for "most recent," it should include any news feed settings you've selected in facebook, since it literally uses the posts visible on https://m.facebook.com/ . it scrapes that, it doesn't use the API, so i can't really apply settings like "most recent" myself.

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!
