### ISSUE TITLE
pasted link with c_user and xs into feedly. did not work.  

### ISSUE THREAD

**Issue by i-SillyGit** [snarfed/facebook-atom#25]
screenshot, with cookie data obscured (note the hard-to-read small grey "no feed found"):  
![facebook-atom feed reader feedly failure](https://user-images.githubusercontent.com/55333129/116223598-af304b00-a71d-11eb-9a00-964d8b840f57.PNG)

Am I doing this right?  Does facebook-atom still work?

**Comment by i-SillyGit** [comment]
I then clicked the green + NEW FEED, and a red box appeared saying FAILED [...].    But when I closed the spinning wheel, then the feed appeared, working.

**Comment by snarfed** [comment]
Sorry for the trouble! Facebook intermittently blocks our scraping, so requests do occasionally fail like this. I'll add a note to the site.

More importantly, the scraping code itself is out of date. I'm in the middle of updating it, just hasn't been a priority yet. Stay tuned.

**Comment by snarfed** [comment]
OK, this should be up and running again. It's still a work in progress, missing pictures and some other bits, but I'll keep working on it.

**Comment by i-SillyGit** [comment]
Thanks :)

**Comment by Siderite** [comment]
Tried it today, the feed is created, but no content.

**Comment by snarfed** [comment]
Hmm! I looked at my own feed just now, and it has content. It's possible your mbasic.facebook.com happened to only have comments, friend requests, ads, etc at that point. Put the feed in your feed reader and see if posts eventually show up!
