### ISSUE TITLE
Not working with feed reader like Feedly

### ISSUE THREAD

**Issue by djmtype** [snarfed/facebook-atom#26]
I've added  my `c_user` and `xs` cookie. This doesn't seem to work for me. I can see the feed, yet nothing is inside it. I have posts within my feed.

**Comment by snarfed** [comment]
Hmm, sorry for the trouble! facebook-atom tries hard to only show direct posts from your friends and people you follow, ie [it filters out all these kinds of posts](https://github.com/snarfed/facebook-atom/blob/main/main.py#L22-L32). What do you see on https://mbasic.facebook.com/ ? Are many or all of the posts there in that blocklist?

**Comment by snarfed** [comment]
Need more follow-up info. Tentatively closing, but feel free to reopen!
