### ISSUE TITLE
Unable to subscribe to Feed

### ISSUE THREAD

**Issue by filipe-silva** [snarfed/facebook-atom#4]
Hello, I don't know if there is something I've missed, but your tutorial was impecable. 
However from the generated link there is no feed. At first it showed me one post, but then it dissappeared. Now it shows nothing.

Any ideas?

**Comment by filipe-silva** [comment]
I've dig a little deeper and it seems there are some syntax errors and unknown tags. Makes most simple rss readers not able to parse it. So far i've only managed to get one rss reader working.

So aside from the issue that might not be a issue, do you use any feed reader? i.e. feedly

**Comment by snarfed** [comment]
sorry for the trouble! and thanks for the report. i see the same behavior with my feed, ie it's often empty and most other times only has one or maybe two posts, but it still does work with my reader, newsblur, and other big readers i tested. i guess they all just fetch it often.

i haven't tested it in many small readers. mind elaborating on the syntax errors, or even better, send a PR?

**Comment by filipe-silva** [comment]
Not sure what PR is. (Its a Pull Request?)
But for the syntax errors, I've checked the return against W3CValidator and it said this:
This feed does not validate.
line 43, column 38: id is not a valid TAG: tag:facebook.com
line 51, column 81: XML parsing error: <unknown>:51:81: not well-formed (invalid token) 
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.
line 2, column 0: Use of unknown namespace: http://activitystrea.ms/spec/1.0/ [help]
<feed xml:lang="en-US"
line 2, column 0: Use of unknown namespace: http://ostatus.org/schema/1.0 [help]
<feed xml:lang="en-US"
line 23, column 95: Unregistered link relationship: avatar [help]
line 24, column 93: Self reference doesn't match document location [help]
... el="self" type="application/atom+xml" />

The troublemaker is prolly the XML parsing error. The rest can be ignored, otherwise it wouldn't work on any reader. The weird part is that it belongs to a feed that the reader I'm using managed to parse!

The full line of the syntax error is the following (xxxx are numbers):
`<a class="link" href="https://www.facebook.com/photo.php?fbid=xxxx&set=p.xxxx&type=1">`

**Comment by snarfed** [comment]
thanks for the info! i know it works in at least three of the top readers as is (the ones i tested), but you're right, it probably does cause problems in at least some others. i'll fix it soon.

**Comment by filipe-silva** [comment]
If there's anything else I can do to help, just let me know.

**Comment by snarfed** [comment]
just recording these for myself for later: https://validator.w3.org/ , https://validator.w3.org/feed/

**Comment by snarfed** [comment]
main fix: snarfed/activitystreams-unofficial@191430119230399b091053dc6870da65f0397b12

**Comment by snarfed** [comment]
ok @blackdragon1, the feed should validate as atom now. feel free to try again!

**Comment by filipe-silva** [comment]
Everything checks out fine.
Right from start firefox parses it and shows the feeds, also tried on CommaFeed, TinyTinyRSS and it worked as well.
Thanks for all your work, I've been searching for an app like this for years!
