### ISSUE TITLE
New applications are not automatically granted read_stream permission

### ISSUE THREAD

**Issue by nogweii** [snarfed/facebook-atom#5]
You must now submit for a review by Facebook before being granted the permission.

**Comment by nogweii** [comment]
Ah, sorry, you already are aware of this (see #2).

**Comment by snarfed** [comment]
yup, sad. basically no one gets read_stream except partners. that's why i changed http://facebook-atom.appspot.com/ to have users make their own FB apps, since you get read_stream for yourself on your own apps.

**Comment by nogweii** [comment]
Are you sure about that? When following the instructions on the webpage my newly created app did not have the permission.

They have also updated the Developer Dashboard, showing the API version. My app shows 'v2.4'. (And #2 references changes made in v2.2)

It's possible there is a new step needed.

![facebook_read_stream_error](https://cloud.githubusercontent.com/assets/14547/8814950/a164ca06-2fc7-11e5-9497-cb5876cf0ba7.png)

EDIT: My fresh app wasn't called "My Atom Feeds", so I created yet another app. Perhaps Facebook had special-cased the particular name? No dice though. Getting the `read_stream` error still.

**Comment by snarfed** [comment]
@evaryont true! we need API v2.2, but it sounds like facebook sets the current API version when you create an app as a low watermark, and may not let that app use a previous API version. that's a problem. tracking this in #6.
