### ISSUE TITLE
/me/home is deprecated in API v2.4

### ISSUE THREAD

**Issue by darren3** [snarfed/facebook-atom#6]
Hello, I have just tried setting up a feed and followed your instructions on setting up a facebook app. When I fill in my App id and App secret and hit Get my Feed I get the following error "Invalid Scopes: read_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions". Have you come across this before?

**Comment by snarfed** [comment]
thanks for the heads up @darren3! looks like FB is [deprecating the `/me/home` endpoint and `read_stream` permissions in API v2.4](https://developers.facebook.com/docs/apps/changelog#v2_4_deprecations). ugh. not sure what we can switch to instead, if anything. ugh. :/

**Comment by snarfed** [comment]
the silver lining is that [API v2.2, which we use, will keep working until march 25 2017](https://developers.facebook.com/docs/apps/changelog).

**Comment by darren3** [comment]
How do we set the app to use API v2.2? Seems to default to 2.4 when I set it up?

**Comment by snarfed** [comment]
@darren3 good question! it sounds like facebook sets the current API version when you create an app as a low watermark, and may not let that app use a previous API version. if so, that's a problem for us. :/

**Comment by snarfed** [comment]
yup. from https://developers.facebook.com/docs/apps/versions#calling_older_versions:

> An app can make calls to the version of the API that was the latest available when the app was created, as well as any newer, un-deprecated versions launched after the app is created.

well, shit.

**Comment by snarfed** [comment]
i've been googling all different combinations of _facebook_, _api_, _2.4_, _/me/home_, and _read_stream_, but haven't found anything useful. it looks like the news feed may just not be available via the API to normal apps any more.

...and what's worse, it looks like that goes into effect for all apps (not just new ones) in october 2015, not 2017. ugh.

**Comment by snarfed** [comment]
asked on SO: http://stackoverflow.com/questions/31801856/facebook-api-replacement-for-me-home-to-get-users-news-feed. fingers crossed!

**Comment by snarfed** [comment]
no answer on SO. i ended up rewriting this to scrape m.facebook.com with users' cookies instead. :/ sigh. at least it will survive the API change!

**Comment by darren3** [comment]
great, will have a look tomorrow. thanks.
