### ISSUE TITLE
Try using but not working

### ISSUE THREAD

**Issue by manuel-sejourne** [snarfed/facebook-atom#7]
Great Tools ! But I have no feeds...

![httpsfacebook-atom appspot comcookiec_user 1112971806 xs 19 3atqouoogblp-c0w 3a2 3a1435752815 3a13984 - google chrome](https://cloud.githubusercontent.com/assets/1440791/9324422/51444b18-458a-11e5-984e-03e1b4ff4295.jpg)

I tried to replace the 2 params :

https://facebook-atom.appspot.com/cookie?c_user=USER_ID_COOKIE_VALUE&xs=XS_COOKIE_VALUE

is your app engine https://facebook-atom.appspot.com/ up ?

Can I do something wrong ?

Thanks for helping ;-)

**Comment by snarfed** [comment]
hi, thanks for the kind words! looks like your two cookie values are probably wrong. they should look something like this:

```
?c_user=212038&xs=123%3AAbC456DeF789GhI%3A2%3A2468097531%3A9876
```

i'll work on adding better error checking so that it tells you when this happens instead of returning an empty feed.

**Comment by snarfed** [comment]
fixed by bef7dcacdc6425a797312dae0fa17a430c6d5ccd

**Comment by manuel-sejourne** [comment]
Hi!

I think my cookies are ok. I have a French Facebook account, maybe the cause?
Indeed, if you can put error checking, it will be good ;-)

Waiting your feedback and thanks for your work ;-)

**Comment by manuel-sejourne** [comment]
I re-tried and the request is ok but I got this : 

<?xml version="1.0" encoding="UTF-8"?>
<feed xml:lang="en-US" xmlns="http://www.w3.org/2005/Atom">
<id>https://facebook-atom.appspot.com/</id>
<title>facebook-atom feed</title>
<logo>https://static.xx.fbcdn.net/rsrc.php/v2/yp/r/eZuLK-TGwK1.png</logo>
<updated>2015-08-19T07:57:41.361770</updated>

<link href="https://m.facebook.com/" rel="alternate" type="text/html" />
<link href="https://facebook-atom.appspot.com/"
      rel="self" type="application/atom+xml" />

</feed>

Any idea ? ;-)

**Comment by snarfed** [comment]
thanks for your patience @manuel-sejourne! turns out you were right, i wasn't handling all languages correctly. i think i've fixed that. fingers crossed!

**Comment by manuel-sejourne** [comment]
It works ! thanks
